### ISSUE TITLE
There's no output

### ISSUE THREAD

**Issue by trajano** [Erikkre/DevhausInterview_DockerFizzBuzz#1]
![image](https://user-images.githubusercontent.com/110627/119384226-5dce9980-bc92-11eb-826b-cb5fd3c6d912.png)

**Comment by Erikkre** [comment]
Try running docker run -p 54321:54321 erikkre/devhausinterview
and then hitting http://127.0.0.1:54321/fizzbuzz from the readme. I will add that to the script.

**Comment by trajano** [comment]
Yup I noticed it afterwards.  I am writing up the evaluation of the assignment right now.
